"""PR comment renderers for GitHub-facing qaestro output."""

from __future__ import annotations

from dataclasses import dataclass

from src.core.contracts import QAReport


@dataclass(frozen=True)
class PRCommentPayload:
    """Rendered payload ready to be posted to a pull request conversation."""

    repo_full_name: str
    pr_number: int
    body: str


class GitHubPRCommentRenderer:
    """Render QA reports as GitHub PR comment bodies.

    The renderer formats already-produced facts. It deliberately does not decide
    risk, choose validation actions, or call GitHub. Current report content still
    comes from stub workflow components; later milestones can replace those
    producers without renaming this channel-specific renderer.
    """

    def render(self, report: QAReport, *, correlation_id: str) -> PRCommentPayload:
        if report.pr_number is None:
            raise ValueError("PR comment renderer requires report.pr_number")

        body = "\n".join(
            [
                "## Qaestro QA Report",
                "",
                f"Repository: `{report.repo_full_name}`",
                f"Pull request: `#{report.pr_number}`",
                f"Event: `{report.event_id}`",
                "",
                report.summary_markdown or report.impact.summary,
                "",
                "### Impact Areas",
                *_impact_lines(report),
                "",
                "### Strategy",
                report.strategy.reasoning or "No strategy reasoning provided.",
                *_action_lines(report),
                "",
                "### Validation",
                *_validation_lines(report),
                "",
                f"Correlation ID: `{correlation_id}`",
                "",
                "---",
                "🤖 *Generated by Qaestro*",
            ]
        )
        return PRCommentPayload(
            repo_full_name=report.repo_full_name,
            pr_number=report.pr_number,
            body=body,
        )


def _impact_lines(report: QAReport) -> list[str]:
    if not report.impact.areas:
        return ["- No impact areas identified in stub mode."]
    return [f"- **{area.module}** ({area.risk_level.value}): {area.description}" for area in report.impact.areas]


def _action_lines(report: QAReport) -> list[str]:
    if not report.strategy.actions:
        return ["", "Recommended actions: none in stub mode."]
    lines = ["", "Recommended actions:"]
    lines.extend(
        f"- {action.description} (`{action.action_type.value}` → `{action.target}`)"
        for action in report.strategy.actions
    )
    return lines


def _validation_lines(report: QAReport) -> list[str]:
    if not report.validations:
        return ["Validation skipped — runtime validation has not produced results yet."]
    return [
        f"- Validation: {result.outcome.value} — {result.details or result.action.description}"
        for result in report.validations
    ]
