"""PR comment and review renderers for GitHub-facing qaestro output."""

from __future__ import annotations

from dataclasses import dataclass, replace
from typing import TYPE_CHECKING, Any

from src.adapters.connectors.github import ReviewCommentInput
from src.core.contracts import CIFeedbackContext, CIHistoricalEvidence, CIObservation, QAReport, ValidationResult
from src.shared.redaction import SecretRedactor, redact_text, redact_value

if TYPE_CHECKING:
    from src.runtime.orchestrator.pr_triage import PRWorkflowTriage

_ATTRIBUTION = "---\n🤖 *Generated by Qaestro*"


@dataclass(frozen=True)
class PRCommentPayload:
    """Rendered payload ready to be posted to a pull request conversation."""

    repo_full_name: str
    pr_number: int
    body: str


@dataclass(frozen=True)
class PRReviewComment:
    """One inline comment intended for GitHub's official PR review UI."""

    path: str
    body: str
    line: int | None = None
    side: str = "RIGHT"
    start_line: int | None = None
    start_side: str = ""

    @property
    def is_mapped(self) -> bool:
        return bool(self.path.strip()) and self.line is not None

    def with_attribution(self) -> PRReviewComment:
        return replace(self, body=_with_attribution(self.body))

    def to_client_input(self) -> ReviewCommentInput:
        if not self.is_mapped:
            raise ValueError("review comment requires path and line")
        return ReviewCommentInput(
            path=self.path,
            body=_with_attribution(self.body),
            line=self.line,
            side=self.side or "RIGHT",
            start_line=self.start_line,
            start_side=self.start_side or self.side or "RIGHT",
        )


@dataclass(frozen=True)
class PRReviewPayload:
    """Official GitHub PR review payload, distinct from the managed summary comment."""

    repo_full_name: str
    pr_number: int
    head_sha: str
    body: str
    event: str = "COMMENT"
    comments: tuple[PRReviewComment, ...] = ()

    @classmethod
    def from_tool_input(cls, raw: dict[str, Any]) -> PRReviewPayload:
        comments = tuple(_review_comment_from_raw(item) for item in raw.get("comments", ()))
        return cls(
            repo_full_name=str(raw.get("repo_full_name", "")),
            pr_number=int(raw.get("pr_number", 0)),
            head_sha=str(raw.get("head_sha", "")),
            body=str(raw.get("body", "")),
            event=str(raw.get("event", "COMMENT")) or "COMMENT",
            comments=comments,
        )

    def prepared_for_submission(self) -> PRReviewPayload:
        mapped = tuple(
            _validated_review_comment(_redacted_review_comment(comment)).with_attribution()
            for comment in self.comments
            if comment.is_mapped
        )
        unmapped = tuple(_redacted_review_comment(comment) for comment in self.comments if not comment.is_mapped)
        body = _redact_external_text(self.body, redact_urls=True)
        if unmapped:
            body = _append_unmapped_findings(body, unmapped)
        return replace(self, body=_with_attribution(body), event="COMMENT", comments=mapped)

    def to_client_comments(self) -> tuple[ReviewCommentInput, ...]:
        return tuple(comment.to_client_input() for comment in self.comments)

    def with_correlation_id(self, correlation_id: str) -> PRReviewPayload:
        marker = f"Correlation ID: `{correlation_id}`"
        if marker in self.body:
            return self
        return replace(self, body=f"{self.body.strip()}\n\n{marker}" if self.body.strip() else marker)


def _redact_external_text(text: str, *, redact_urls: bool = False) -> str:
    return SecretRedactor(redact_urls=redact_urls).redact_text(text)


def _redacted_review_comment(comment: PRReviewComment) -> PRReviewComment:
    return replace(comment, body=_redact_external_text(comment.body, redact_urls=True))


class GitHubPRCommentRenderer:
    """Render QA reports as GitHub PR comment bodies.

    The renderer formats already-produced facts. It deliberately does not decide
    risk, choose validation actions, or call GitHub.
    """

    def render(
        self,
        report: QAReport,
        *,
        correlation_id: str,
        triage: PRWorkflowTriage | None = None,
        ci_feedback: CIFeedbackContext | None = None,
    ) -> PRCommentPayload:
        if report.pr_number is None:
            raise ValueError("PR comment renderer requires report.pr_number")
        ci_feedback = ci_feedback if ci_feedback is not None else report.ci_feedback

        body = "\n".join(
            [
                "## Behaviour Impact Report",
                "",
                f"Repository: `{report.repo_full_name}`",
                f"Pull request: `#{report.pr_number}`",
                f"Event: `{report.event_id}`",
                f"Overall risk: **{_overall_risk_label(report, triage)}**",
                *_triage_lines(triage),
                "",
                "### Change Summary",
                report.summary_markdown or report.impact.summary,
                "",
                "### Diff Stats",
                *_diff_stat_lines(report),
                *_ci_feedback_section(ci_feedback),
                "",
                "### Impact Areas",
                *_impact_lines(report),
                "",
                "### Strategy Evidence",
                report.strategy.reasoning or "No strategy reasoning provided.",
                *_action_lines(report),
                "",
                "### Validation",
                *_validation_lines(report),
                "",
                f"Correlation ID: `{correlation_id}`",
                "",
                _ATTRIBUTION,
            ]
        )
        return PRCommentPayload(
            repo_full_name=report.repo_full_name,
            pr_number=report.pr_number,
            body=_redact_external_text(body),
        )


def _validated_review_comment(comment: PRReviewComment) -> PRReviewComment:
    if comment.line is None or comment.line <= 0:
        raise ValueError("review comment line must be a positive integer")
    if comment.side != "RIGHT":
        raise ValueError("review comment side must be RIGHT for qaestro output")
    if comment.start_line is not None:
        if comment.start_line <= 0:
            raise ValueError("review comment start_line must be a positive integer")
        if comment.start_line > comment.line:
            raise ValueError("review comment start_line must be less than or equal to line")
        if comment.start_side and comment.start_side != "RIGHT":
            raise ValueError("review comment start_side must be RIGHT for qaestro output")
    return comment


def _review_comment_from_raw(raw: object) -> PRReviewComment:
    if not isinstance(raw, dict):
        raise ValueError("review comment must be an object")
    line = _optional_int(raw.get("line"))
    start_line = _optional_int(raw.get("start_line"))
    return PRReviewComment(
        path=str(raw.get("path", "")),
        body=str(raw.get("body", "")),
        line=line,
        side=str(raw.get("side", "RIGHT")) or "RIGHT",
        start_line=start_line,
        start_side=str(raw.get("start_side", "")),
    )


def _optional_int(value: object) -> int | None:
    if value is None or value == "":
        return None
    return int(str(value))


def _with_attribution(body: str) -> str:
    clean_body = body.strip()
    if "Generated by Qaestro" in clean_body:
        return clean_body
    if not clean_body:
        return _ATTRIBUTION
    return f"{clean_body}\n\n{_ATTRIBUTION}"


def _append_unmapped_findings(body: str, comments: tuple[PRReviewComment, ...]) -> str:
    lines = [body.strip(), "", "### Unmapped inline findings"] if body.strip() else ["### Unmapped inline findings"]
    for comment in comments:
        path = comment.path.strip() or "unknown path"
        lines.append(f"- `{path}`: {comment.body.strip()}")
    return "\n".join(lines)


def _triage_lines(triage: PRWorkflowTriage | None) -> list[str]:
    if triage is None:
        return []
    allowed = ", ".join(stage.value for stage in triage.allowed_stages) or "none"
    return [
        f"Workflow depth: **{triage.depth.value.upper()}**",
        f"Triage rationale: {triage.rationale}",
        f"Triaged analysis/validation stages: `{allowed}`",
    ]


def _overall_risk_label(report: QAReport, triage: PRWorkflowTriage | None) -> str:
    del triage
    return report.impact.overall_risk.value.replace("_", " ").upper()


def _diff_stat_lines(report: QAReport) -> list[str]:
    stats = report.impact.raw_diff_stats
    if not stats:
        return ["- Diff statistics unavailable."]
    status_counts = _status_counts(stats)
    status_line = "- File status counts: unavailable."
    if status_counts:
        status_line = "- File status counts: " + ", ".join(f"{status} `{count}`" for status, count in status_counts)
    return [
        f"- Files changed: `{stats.get('files_changed', 0)}`",
        f"- Additions/deletions: `+{stats.get('additions', 0)}/-{stats.get('deletions', 0)}`",
        status_line,
    ]


def _status_counts(stats: dict[str, int | str]) -> list[tuple[str, int]]:
    """Return known status counters first, then any future counters by name."""
    preferred_order = (
        "files_added",
        "files_modified",
        "files_removed",
        "files_renamed",
        "files_copied",
        "files_unchanged",
        "files_unknown",
    )
    known = [(key, _int_stat(stats[key])) for key in preferred_order if key in stats]
    extra = sorted(
        (key, _int_stat(value))
        for key, value in stats.items()
        if key.startswith("files_") and key not in {"files_changed", *preferred_order}
    )
    return [(_status_label(key), value) for key, value in (*known, *extra)]


def _int_stat(value: int | str) -> int:
    return value if isinstance(value, int) else 0


def _status_label(key: str) -> str:
    return key.removeprefix("files_").replace("_", " ")


def _ci_feedback_section(ci_feedback: CIFeedbackContext | None) -> list[str]:
    """Render already-produced CI/check facts without making strategy decisions."""
    if ci_feedback is None:
        return []
    lines = [
        "",
        "### CI / Check Feedback",
        f"- Current head: {_inline_code_span(ci_feedback.current_head_sha)}",
        f"- Readiness: **{_markdown_text(ci_feedback.readiness.value.replace('_', ' ').upper())}**",
    ]
    if ci_feedback.pending_checks:
        lines.append("- Pending checks: " + ", ".join(_inline_code_span(check) for check in ci_feedback.pending_checks))
    if ci_feedback.current_observations:
        lines.append("- Current-head observations:")
        lines.extend(f"  - {_ci_observation_line(observation)}" for observation in ci_feedback.current_observations)
    else:
        lines.append("- Current-head observations: none recorded.")
    historical_lines = _historical_ci_lines(ci_feedback.historical_evidence)
    if historical_lines:
        lines.append("- Historical CI evidence from superseded heads:")
        lines.extend(historical_lines)
    return lines


def _ci_observation_line(observation: CIObservation) -> str:
    conclusion = _inline_code_span(observation.conclusion.strip().lower() or "unknown")
    line = f"**{_markdown_text(observation.workflow_name)}** — {conclusion}"
    if observation.failed_jobs:
        line += "; failed jobs: " + ", ".join(_inline_code_span(job) for job in observation.failed_jobs)
    links = _ci_observation_links(observation)
    if links:
        line += f" ({'; '.join(links)})"
    return line


def _ci_observation_links(observation: CIObservation) -> list[str]:
    links: list[str] = []
    if observation.run_url:
        links.append(f"[run]({observation.run_url})")
    if observation.logs_url:
        links.append(f"[logs]({observation.logs_url})")
    return links


def _historical_ci_lines(evidence: tuple[CIHistoricalEvidence, ...]) -> list[str]:
    lines: list[str] = []
    for item in evidence:
        if not item.observations:
            continue
        summary = "; ".join(_ci_observation_line(observation) for observation in item.observations)
        lines.append(f"  - {_inline_code_span(item.head_sha)}: {summary}")
    return lines


def _inline_code_span(text: str) -> str:
    """Return a Markdown inline-code span that can contain backticks safely."""
    longest_run = _longest_backtick_run(text)
    delimiter = "`" * (longest_run + 1)
    if text.startswith("`") or text.endswith("`"):
        return f"{delimiter} {text} {delimiter}"
    return f"{delimiter}{text}{delimiter}"


def _longest_backtick_run(text: str) -> int:
    longest = current = 0
    for char in text:
        if char == "`":
            current += 1
            longest = max(longest, current)
        else:
            current = 0
    return longest


def _markdown_text(text: str) -> str:
    return text.replace("[", "\\[").replace("*", "\\*").replace("_", "\\_")


def _impact_lines(report: QAReport) -> list[str]:
    if not report.impact.areas:
        return ["- No impact areas identified."]
    return [
        (
            f"- **{area.module}** ({area.risk_level.value}): {area.description}"
            f" — files: {', '.join(f'`{file}`' for file in area.affected_files[:5])}"
        )
        for area in report.impact.areas
    ]


def _action_lines(report: QAReport) -> list[str]:
    if not report.strategy.actions:
        return ["", "Evidence-backed actions: none."]
    lines = ["", "Evidence-backed actions:"]
    lines.extend(
        (
            f"- P{action.priority} **{action.description}** "
            f"(`{action.action_type.value}` → `{action.target}`)"
            f" — {action.rationale}"
        )
        for action in sorted(report.strategy.actions, key=lambda item: (-item.priority, item.description))
    )
    if report.strategy.knowledge_refs:
        lines.append("")
        lines.append("Knowledge refs: " + ", ".join(f"`{ref}`" for ref in report.strategy.knowledge_refs))
    return lines


def _validation_lines(report: QAReport) -> list[str]:
    if not report.validations:
        return ["Validation not executed in this step — recommendations only."]
    lines: list[str] = []
    for result in report.validations:
        lines.extend(_validation_result_lines(result))
    return lines


def _validation_result_lines(result: ValidationResult) -> list[str]:
    action = result.action
    lines = [
        f"- **{action.action_type.value.replace('_', ' ').upper()}** — {action.description}",
        f"  - Target: {_inline_code_span(action.target)}",
        f"  - Outcome: **{_markdown_text(result.outcome.value.upper())}**",
    ]
    if result.duration_seconds > 0:
        lines.append(f"  - Duration: {_inline_code_span(f'{result.duration_seconds:.3f}s')}")
    detail = redact_text(result.details or action.rationale, redact_urls=True)
    if detail:
        lines.append(f"  - Details: {detail}")
    if result.artifacts:
        redacted_artifacts = redact_value(result.artifacts, redact_urls=True)
        artifacts = redacted_artifacts if isinstance(redacted_artifacts, tuple) else ()
        links = ", ".join(f"[artifact {index}]({artifact})" for index, artifact in enumerate(artifacts, start=1))
        lines.append(f"  - Artifacts: {links}")
    return lines
