"""Tests for official GitHub review output surface."""

from __future__ import annotations

from src.adapters.connectors.github import CommentResult, ReviewCommentInput, ReviewResult
from src.adapters.renderers import PRCommentPayload, PRReviewComment, PRReviewPayload
from src.runtime.orchestrator import ToolRuntimePROutputPoster
from src.runtime.stages import WorkflowStage
from src.runtime.tools import ToolAuditEntry, ToolCall, ToolResult


class RecordingRuntime:
    def __init__(self, *, current_head_sha: str = "abc123", existing_reviews: tuple[ReviewResult, ...] = ()) -> None:
        self.calls: list[ToolCall] = []
        self.current_head_sha = current_head_sha
        self.existing_reviews = existing_reviews
        self.outputs = {
            "github.pr.comment.create_or_update": CommentResult(
                id=99,
                html_url="https://github.com/octocat/hello-world/pull/7#issuecomment-99",
                body="summary body",
            ),
            "github.pr.review.create": ReviewResult(
                id=42,
                html_url="https://github.com/octocat/hello-world/pull/7#pullrequestreview-42",
                state="COMMENTED",
                body="review body",
                commit_id=current_head_sha,
            ),
        }

    @property
    def audit_log(self) -> tuple[ToolAuditEntry, ...]:
        return ()

    def execute(self, call: ToolCall) -> ToolResult:
        self.calls.append(call)
        if call.name == "github.pr.view":
            return ToolResult(call=call, ok=True, output={"head_sha": self.current_head_sha})
        if call.name == "github.pr.review.list":
            return ToolResult(call=call, ok=True, output=self.existing_reviews)
        return ToolResult(call=call, ok=True, output=self.outputs[call.name])


def test_output_poster_submits_official_review_separately_from_summary_comment() -> None:
    runtime = RecordingRuntime()
    poster = ToolRuntimePROutputPoster(runtime)
    comment_payload = PRCommentPayload(repo_full_name="octocat/hello-world", pr_number=7, body="summary body")
    review_payload = PRReviewPayload(
        repo_full_name="octocat/hello-world",
        pr_number=7,
        head_sha="abc123",
        body="review body",
        event="COMMENT",
        comments=(
            PRReviewComment(
                path="src/app.py",
                body="inline body",
                line=12,
                side="RIGHT",
            ),
        ),
    )

    result = poster.post_outputs(comment_payload, review_payload=review_payload, correlation_id="corr-review")

    assert result.review is not None
    assert result.review.id == 42
    assert [(call.stage, call.name) for call in runtime.calls] == [
        (WorkflowStage.OUTPUT, "github.pr.view"),
        (WorkflowStage.OUTPUT, "github.pr.review.list"),
        (WorkflowStage.OUTPUT, "github.pr.comment.create_or_update"),
        (WorkflowStage.OUTPUT, "github.pr.review.create"),
    ]
    review_call = runtime.calls[3]
    assert review_call.input == {
        "repo_full_name": "octocat/hello-world",
        "pr_number": 7,
        "head_sha": "abc123",
        "body": "review body\n\n---\n🤖 *Generated by Qaestro*\n\nCorrelation ID: `corr-review`",
        "event": "COMMENT",
        "comments": (
            {
                "path": "src/app.py",
                "body": "inline body\n\n---\n🤖 *Generated by Qaestro*",
                "line": 12,
                "side": "RIGHT",
            },
        ),
    }


def test_output_poster_rejects_stale_review_head_before_writing() -> None:
    runtime = RecordingRuntime(current_head_sha="new-head")
    poster = ToolRuntimePROutputPoster(runtime)
    payload = PRReviewPayload(
        repo_full_name="octocat/hello-world",
        pr_number=7,
        head_sha="old-head",
        body="review body",
    )

    try:
        poster.post_review(payload, correlation_id="corr-stale")
    except RuntimeError as exc:
        assert "stale head" in str(exc)
    else:  # pragma: no cover - assertion clarity
        raise AssertionError("stale review head was not rejected")

    assert [call.name for call in runtime.calls] == ["github.pr.view"]


def test_output_poster_skips_duplicate_review_for_same_head_and_correlation() -> None:
    existing = ReviewResult(
        id=77,
        html_url="https://github.com/octocat/hello-world/pull/7#pullrequestreview-77",
        state="COMMENTED",
        body="review body\n\nCorrelation ID: `corr-dup`",
        commit_id="abc123",
    )
    runtime = RecordingRuntime(existing_reviews=(existing,))
    poster = ToolRuntimePROutputPoster(runtime)
    payload = PRReviewPayload(
        repo_full_name="octocat/hello-world",
        pr_number=7,
        head_sha="abc123",
        body="review body\n\nCorrelation ID: `corr-dup`",
    )

    result = poster.post_review(payload, correlation_id="corr-dup")

    assert result == existing
    assert [call.name for call in runtime.calls] == ["github.pr.view", "github.pr.review.list"]


def test_review_payload_degrades_unmapped_inline_comments_into_review_body() -> None:
    payload = PRReviewPayload(
        repo_full_name="octocat/hello-world",
        pr_number=7,
        head_sha="abc123",
        body="review body",
        comments=(
            PRReviewComment(path="src/app.py", body="mapped", line=12),
            PRReviewComment(path="src/missing.py", body="unmapped finding"),
        ),
    )

    prepared = payload.prepared_for_submission()

    assert len(prepared.comments) == 1
    assert prepared.comments[0].body == "mapped\n\n---\n🤖 *Generated by Qaestro*"
    assert "Unmapped inline findings" in prepared.body
    assert "src/missing.py" in prepared.body
    assert "unmapped finding" in prepared.body
    assert prepared.body.endswith("🤖 *Generated by Qaestro*")


def test_review_tool_input_normalizes_comment_payload_shape() -> None:
    raw = {
        "repo_full_name": "octocat/hello-world",
        "pr_number": 7,
        "head_sha": "abc123",
        "body": "review body",
        "event": "COMMENT",
        "comments": (
            {"path": "src/app.py", "body": "inline", "line": 12, "side": "RIGHT"},
            {"path": "src/app.py", "body": "range", "start_line": 10, "line": 12, "side": "RIGHT"},
        ),
    }

    payload = PRReviewPayload.from_tool_input(raw)

    assert payload.comments == (
        PRReviewComment(path="src/app.py", body="inline", line=12, side="RIGHT"),
        PRReviewComment(path="src/app.py", body="range", line=12, start_line=10, side="RIGHT"),
    )
    assert payload.to_client_comments() == (
        ReviewCommentInput(
            path="src/app.py",
            body="inline\n\n---\n🤖 *Generated by Qaestro*",
            line=12,
            side="RIGHT",
            start_side="RIGHT",
        ),
        ReviewCommentInput(
            path="src/app.py",
            body="range\n\n---\n🤖 *Generated by Qaestro*",
            line=12,
            side="RIGHT",
            start_line=10,
            start_side="RIGHT",
        ),
    )


def test_review_payload_forces_comment_event_for_official_review_surface() -> None:
    payload = PRReviewPayload(
        repo_full_name="octocat/hello-world",
        pr_number=7,
        head_sha="abc123",
        body="review body",
        event="REQUEST_CHANGES",
    )

    assert payload.prepared_for_submission().event == "COMMENT"


def test_review_payload_rejects_invalid_inline_comment_shapes() -> None:
    invalid_payloads = (
        PRReviewPayload(
            repo_full_name="octocat/hello-world",
            pr_number=7,
            head_sha="abc123",
            body="review body",
            comments=(PRReviewComment(path="src/app.py", body="bad", line=0),),
        ),
        PRReviewPayload(
            repo_full_name="octocat/hello-world",
            pr_number=7,
            head_sha="abc123",
            body="review body",
            comments=(PRReviewComment(path="src/app.py", body="bad", line=12, side="LEFT"),),
        ),
        PRReviewPayload(
            repo_full_name="octocat/hello-world",
            pr_number=7,
            head_sha="abc123",
            body="review body",
            comments=(PRReviewComment(path="src/app.py", body="bad", line=12, start_line=14),),
        ),
    )

    for payload in invalid_payloads:
        try:
            payload.prepared_for_submission()
        except ValueError:
            continue
        raise AssertionError("invalid inline review comment shape was not rejected")


def test_output_poster_preflights_review_create_before_summary_comment() -> None:
    runtime = RecordingRuntime(current_head_sha="new-head")
    poster = ToolRuntimePROutputPoster(runtime)
    comment_payload = PRCommentPayload(repo_full_name="octocat/hello-world", pr_number=7, body="summary body")
    review_payload = PRReviewPayload(
        repo_full_name="octocat/hello-world",
        pr_number=7,
        head_sha="old-head",
        body="review body",
    )

    try:
        poster.post_outputs(comment_payload, review_payload=review_payload, correlation_id="corr-stale")
    except RuntimeError as exc:
        assert "stale head" in str(exc)
    else:  # pragma: no cover - assertion clarity
        raise AssertionError("stale review did not block output posting")

    assert [call.name for call in runtime.calls] == ["github.pr.view"]


def test_output_poster_adds_correlation_marker_before_duplicate_lookup() -> None:
    existing = ReviewResult(
        id=77,
        html_url="https://github.com/octocat/hello-world/pull/7#pullrequestreview-77",
        state="COMMENTED",
        body="review body\n\nCorrelation ID: `corr-auto`",
        commit_id="abc123",
    )
    runtime = RecordingRuntime(existing_reviews=(existing,))
    poster = ToolRuntimePROutputPoster(runtime)
    payload = PRReviewPayload(
        repo_full_name="octocat/hello-world",
        pr_number=7,
        head_sha="abc123",
        body="review body",
    )

    result = poster.post_review(payload, correlation_id="corr-auto")

    assert result == existing
    assert [call.name for call in runtime.calls] == ["github.pr.view", "github.pr.review.list"]


def test_output_poster_preflights_duplicate_review_before_summary_comment() -> None:
    existing = ReviewResult(
        id=77,
        html_url="https://github.com/octocat/hello-world/pull/7#pullrequestreview-77",
        state="COMMENTED",
        body="review body\n\nCorrelation ID: `corr-existing`",
        commit_id="abc123",
    )
    runtime = RecordingRuntime(existing_reviews=(existing,))
    poster = ToolRuntimePROutputPoster(runtime)
    comment_payload = PRCommentPayload(repo_full_name="octocat/hello-world", pr_number=7, body="summary body")
    review_payload = PRReviewPayload(
        repo_full_name="octocat/hello-world",
        pr_number=7,
        head_sha="abc123",
        body="review body",
    )

    result = poster.post_outputs(comment_payload, review_payload=review_payload, correlation_id="corr-existing")

    assert result.review == existing
    assert [call.name for call in runtime.calls] == [
        "github.pr.view",
        "github.pr.review.list",
        "github.pr.comment.create_or_update",
    ]


def test_pass_validation_evidence_stays_in_review_body_without_inline_comment() -> None:
    payload = PRReviewPayload(
        repo_full_name="octocat/hello-world",
        pr_number=7,
        head_sha="abc123",
        body="review body",
        comments=(PRReviewComment(path="src/app.py", body="Runtime validation passed for `GET /health`: ok", line=12),),
    )

    prepared = payload.prepared_for_submission()

    assert prepared.comments == ()
    assert "Runtime validation passed" in prepared.body
    assert "Unmapped inline findings" in prepared.body
