"""Tests for GitHub PR comment rendering."""

from __future__ import annotations

from src.adapters.renderers import GitHubPRCommentRenderer, PRCommentPayload
from src.core.contracts import (
    ActionType,
    BehaviourImpact,
    ImpactArea,
    QAReport,
    RiskLevel,
    StrategyAction,
    StrategyResult,
    ValidationOutcome,
    ValidationResult,
)
from src.runtime.orchestrator import PRWorkflowDepth, PRWorkflowTriage
from src.runtime.stages import WorkflowStage


def _qa_report() -> QAReport:
    action = StrategyAction(
        action_type=ActionType.RUN_TESTS,
        description="Run connector tests",
        target="tests/adapters/connectors",
        priority=2,
        rationale="Connector files changed.",
    )
    return QAReport(
        event_id="evt-001",
        repo_full_name="Kimcheolhui/qaestro",
        pr_number=31,
        impact=BehaviourImpact(
            summary="Connector files changed",
            areas=(
                ImpactArea(
                    module="adapters/connectors",
                    description="GitHub connector changed",
                    risk_level=RiskLevel.MEDIUM,
                    affected_files=("src/adapters/connectors/github/client.py",),
                ),
            ),
            overall_risk=RiskLevel.MEDIUM,
            raw_diff_stats={
                "files_changed": 4,
                "additions": 120,
                "deletions": 10,
                "files_added": 1,
                "files_modified": 1,
                "files_removed": 0,
                "files_renamed": 0,
                "files_copied": 1,
                "files_unknown": 1,
            },
        ),
        strategy=StrategyResult(
            actions=(action,),
            reasoning="Run focused tests for connector changes.",
            confidence=0.75,
        ),
        validations=(
            ValidationResult(
                action=action,
                outcome=ValidationOutcome.SKIPPED,
                details="Step 3 does not execute runtime validation yet.",
            ),
        ),
        summary_markdown="Connector files changed.",
    )


def test_github_pr_comment_renderer_turns_qa_report_into_pr_comment_payload():
    renderer = GitHubPRCommentRenderer()

    payload = renderer.render(_qa_report(), correlation_id="corr-001")

    assert isinstance(payload, PRCommentPayload)
    assert payload.repo_full_name == "Kimcheolhui/qaestro"
    assert payload.pr_number == 31
    assert "Behaviour Impact Report" in payload.body
    assert "Overall risk: **MEDIUM**" in payload.body
    assert "Connector files changed." in payload.body
    assert "Connector files changed" in payload.body
    assert "Run connector tests" in payload.body
    assert "Files changed: `4`" in payload.body
    assert (
        "File status counts: added `1`, modified `1`, removed `0`, renamed `0`, copied `1`, unknown `1`" in payload.body
    )
    assert "Validation: skipped" in payload.body
    assert "corr-001" in payload.body
    assert "🤖 *Generated by Qaestro*" in payload.body


def test_github_pr_comment_renderer_does_not_require_validation_results():
    report = _qa_report()
    report = QAReport(
        event_id=report.event_id,
        repo_full_name=report.repo_full_name,
        pr_number=report.pr_number,
        impact=report.impact,
        strategy=report.strategy,
        validations=(),
        summary_markdown=report.summary_markdown,
    )

    payload = GitHubPRCommentRenderer().render(report, correlation_id="corr-002")

    assert "Validation not executed in this step" in payload.body
    assert payload.pr_number == 31


def test_github_pr_comment_renderer_marks_triage_only_risk_as_not_assessed() -> None:
    triage = PRWorkflowTriage(
        depth=PRWorkflowDepth.LIGHTWEIGHT,
        rationale="Small documentation update; full analysis was skipped.",
        allowed_stages=(),
    )
    report = _qa_report()
    report = QAReport(
        event_id=report.event_id,
        repo_full_name=report.repo_full_name,
        pr_number=report.pr_number,
        impact=BehaviourImpact(
            summary=triage.rationale,
            areas=(),
            overall_risk=RiskLevel.NOT_ASSESSED,
            raw_diff_stats=report.impact.raw_diff_stats,
        ),
        strategy=StrategyResult(actions=(), reasoning=triage.rationale, confidence=0.0),
        validations=(),
        summary_markdown="Triage-only summary.",
    )

    payload = GitHubPRCommentRenderer().render(report, correlation_id="corr-triage", triage=triage)

    assert "Overall risk: **NOT ASSESSED**" in payload.body
    assert "Overall risk: **LOW**" not in payload.body
    assert "Triaged analysis/validation stages: `none`" in payload.body
    assert "Allowed stages after triage" not in payload.body


def test_github_pr_comment_renderer_lists_triaged_execution_stages_precisely() -> None:
    triage = PRWorkflowTriage(
        depth=PRWorkflowDepth.DEEP,
        rationale="High-impact change signals require full analysis and validation.",
        allowed_stages=(WorkflowStage.ANALYZER, WorkflowStage.STRATEGY, WorkflowStage.VALIDATOR),
    )

    payload = GitHubPRCommentRenderer().render(_qa_report(), correlation_id="corr-deep", triage=triage)

    assert "Overall risk: **MEDIUM**" in payload.body
    assert "Triaged analysis/validation stages: `analyzer, strategy, validator`" in payload.body
    assert "Allowed stages after triage" not in payload.body
