"""Tests for GitHub PR comment rendering."""

from __future__ import annotations

from src.adapters.renderers import GitHubPRCommentRenderer, PRCommentPayload
from src.core.contracts import (
    ActionType,
    BehaviourImpact,
    ImpactArea,
    QAReport,
    RiskLevel,
    StrategyAction,
    StrategyResult,
    ValidationOutcome,
    ValidationResult,
)


def _qa_report() -> QAReport:
    action = StrategyAction(
        action_type=ActionType.RUN_TESTS,
        description="Run connector tests",
        target="tests/adapters/connectors",
        priority=2,
        rationale="Connector files changed.",
    )
    return QAReport(
        event_id="evt-001",
        repo_full_name="Kimcheolhui/qaestro",
        pr_number=31,
        impact=BehaviourImpact(
            summary="Connector files changed",
            areas=(
                ImpactArea(
                    module="adapters/connectors",
                    description="GitHub connector changed",
                    risk_level=RiskLevel.MEDIUM,
                    affected_files=("src/adapters/connectors/github/client.py",),
                ),
            ),
            overall_risk=RiskLevel.MEDIUM,
            raw_diff_stats={"files_changed": 2, "additions": 120, "deletions": 10},
        ),
        strategy=StrategyResult(
            actions=(action,),
            reasoning="Run focused tests for connector changes.",
            confidence=0.75,
        ),
        validations=(
            ValidationResult(
                action=action,
                outcome=ValidationOutcome.SKIPPED,
                details="Step 3 does not execute runtime validation yet.",
            ),
        ),
        summary_markdown="Connector files changed.",
    )


def test_github_pr_comment_renderer_turns_qa_report_into_pr_comment_payload():
    renderer = GitHubPRCommentRenderer()

    payload = renderer.render(_qa_report(), correlation_id="corr-001")

    assert isinstance(payload, PRCommentPayload)
    assert payload.repo_full_name == "Kimcheolhui/qaestro"
    assert payload.pr_number == 31
    assert "Behaviour Impact Report" in payload.body
    assert "Overall risk: **MEDIUM**" in payload.body
    assert "Connector files changed." in payload.body
    assert "Connector files changed" in payload.body
    assert "Run connector tests" in payload.body
    assert "Files changed: `2`" in payload.body
    assert "Validation: skipped" in payload.body
    assert "corr-001" in payload.body
    assert "🤖 *Generated by Qaestro*" in payload.body


def test_github_pr_comment_renderer_does_not_require_validation_results():
    report = _qa_report()
    report = QAReport(
        event_id=report.event_id,
        repo_full_name=report.repo_full_name,
        pr_number=report.pr_number,
        impact=report.impact,
        strategy=report.strategy,
        validations=(),
        summary_markdown=report.summary_markdown,
    )

    payload = GitHubPRCommentRenderer().render(report, correlation_id="corr-002")

    assert "Validation not executed in this step" in payload.body
    assert payload.pr_number == 31
